In [57]:
import os
import h5py
import numpy as np
from powergraph import PowerGrid
from data_utils import loadcase 
from idx import *

In [58]:
powergraph_data = PowerGrid(
    root = os.path.join("..", "data", "powergraph"),
    name="ieee118", 
    datatype="node")

Processing...


../data/powergraph/ieee118/processed_node/data.pt


Done!


In [77]:
powergraph_data[0].y

tensor([[ 0.0000e+00,  0.0000e+00,  1.0231e+00, -1.3583e+01],
        [ 0.0000e+00,  0.0000e+00,  1.0304e+00, -1.2662e+01],
        [ 0.0000e+00,  0.0000e+00,  1.0291e+00, -1.2887e+01],
        [ 0.0000e+00, -1.1910e+01,  0.0000e+00, -1.0252e+01],
        [ 0.0000e+00,  0.0000e+00,  1.0509e+00, -9.9812e+00],
        [ 0.0000e+00,  1.5463e+01,  0.0000e+00, -1.1574e+01],
        [ 0.0000e+00,  0.0000e+00,  1.0434e+00, -1.1686e+01],
        [ 0.0000e+00, -1.3445e+01,  0.0000e+00, -7.0163e+00],
        [ 0.0000e+00,  0.0000e+00,  1.0709e+00, -4.7802e+00],
        [ 0.0000e+00, -7.9081e+01,  0.0000e+00, -2.2622e+00],
        [ 0.0000e+00,  0.0000e+00,  1.0386e+00, -1.1524e+01],
        [ 0.0000e+00,  6.5514e+01,  0.0000e+00, -1.1545e+01],
        [ 0.0000e+00,  0.0000e+00,  1.0255e+00, -1.2122e+01],
        [ 0.0000e+00,  0.0000e+00,  1.0405e+00, -1.1612e+01],
        [ 0.0000e+00, -3.7508e+00,  0.0000e+00, -1.0317e+01],
        [ 0.0000e+00,  0.0000e+00,  1.0399e+00, -1.1237e+01],
        

In [78]:
powergraph_data[0].x

tensor([[ -49.1897,   -8.6600,    0.0000,    1.0000],
        [ -19.2888,   -9.5500,    0.0000,    1.0000],
        [ -37.6145,  -10.6200,    0.0000,    1.0000],
        [ -23.9378,  -12.7400,    1.0512,    2.0000],
        [  -0.0000,   -0.0000,    0.0000,    1.0000],
        [ -45.1527,  -23.3500,    1.0447,    2.0000],
        [ -18.3257,   -2.1200,    0.0000,    1.0000],
        [   5.0000,   -0.0000,    1.0470,    2.0000],
        [  -0.0000,   -0.0000,    0.0000,    1.0000],
        [ 150.0000,   -0.0000,    1.0568,    2.0000],
        [ -67.5154,  -24.4200,    0.0000,    1.0000],
        [  82.6518,  -10.6200,    1.0431,    2.0000],
        [ -32.7901,  -16.9900,    0.0000,    1.0000],
        [ -13.5013,   -1.0600,    0.0000,    1.0000],
        [ -76.8042,  -31.8500,    1.0364,    2.0000],
        [ -24.1133,  -10.6200,    0.0000,    1.0000],
        [ -10.6120,   -3.1800,    0.0000,    1.0000],
        [ -32.8664,  -36.0900,    1.0404,    2.0000],
        [ -38.4021,  -26.540

In [72]:
powergraph_data[0].y[68]

tensor([ 92.2485, -46.4522,   0.0000,   0.0000])

In [61]:
powergraph_data[0].mask

tensor([[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False,  True, False,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False,  True, False,  True],
        [False,  True, False,  True],
        [False,  True, False,  True],
        [Fal

In [62]:
path = os.path.join("..", "data", "powergraph", "ieee118", "raw", "X.mat")

with h5py.File(path, 'r') as f:
    Xpf_refs = f['Xpf'][:, 0]  # Flatten to 1D
    Xpf_resolved = [f[ref][:] for ref in Xpf_refs]  # Dereference each object

# Convert to NumPy array if each element has same shape
Xpf_array = np.array(Xpf_resolved)
print(Xpf_array.shape)

(35040, 4, 118)


In [63]:
Xpf_array[0][1]

array([  -8.66,   -9.55,  -10.62,  -12.74,   -0.  ,  -23.35,   -2.12,
         -0.  ,   -0.  ,   -0.  ,  -24.42,  -10.62,  -16.99,   -1.06,
        -31.85,  -10.62,   -3.18,  -36.09,  -26.54,   -3.18,   -8.49,
         -5.31,   -3.18,   -0.  ,   -0.  ,   -0.  ,  -13.8 ,   -7.43,
         -4.25,   -0.  ,  -28.66,  -24.42,   -9.55,  -27.6 ,   -9.55,
        -18.05,   -0.  ,   -0.  ,  -11.  ,  -23.  ,  -10.  ,  -23.  ,
         -7.  ,   -8.  ,  -22.  ,  -10.  ,   -0.  ,  -11.  ,  -30.  ,
         -4.  ,   -8.  ,   -5.  ,  -11.  ,  -32.  ,  -22.  ,  -18.  ,
         -3.  ,   -3.  , -113.  ,   -3.  ,   -0.  ,  -14.  ,   -0.  ,
         -0.  ,   -0.  ,  -18.  ,   -7.  ,   -0.  ,    0.  ,  -20.  ,
         -0.  ,   -0.  ,   -0.  ,  -27.  ,  -11.  ,  -36.  ,  -28.  ,
        -26.  ,  -32.  ,  -26.  ,   -0.  ,  -27.  ,  -10.  ,   -7.  ,
        -15.  ,  -10.  ,   -0.  ,  -10.  ,   -0.  ,  -42.  ,   -0.  ,
        -10.  ,   -7.  ,  -16.  ,  -31.  ,  -15.  ,   -9.  ,   -8.  ,
         -0.  ,  -18

In [73]:
case_path = "../data/pglib/pglib_opf_case118_ieee.m"
mpc = loadcase(case_path)
bus_types_mpc = mpc["bus"][:, BUS_TYPE].cpu().numpy()

In [74]:
bus_types = Xpf_array[6][3]

In [75]:
mismatch_indices = np.where(bus_types_mpc != bus_types)
mismatch_indices

(array([ 0, 81]),)

In [ ]:
Xpf_array[0][0]

array([ -49.18965146,  -19.28881235,  -37.61454693,  -23.93775933,
         -0.        ,  -45.15272719,  -18.32573458,    5.000002  ,
         -0.        ,  150.00002426,  -67.51538604,   82.65182673,
        -32.79007243,  -13.50126008,  -76.80419647,  -24.11328685,
        -10.61202677,  -32.8664292 ,  -38.40209716,  -17.36265681,
        -13.50126008,   -9.64894899,   -6.75063004,    5.00000193,
        100.00004738,  349.999987  ,  -51.8016763 ,  -16.39957903,
        -23.15020907,   -0.        ,  -33.47594168,  -31.90335166,
        -22.1871313 ,  -48.90335736,  -31.82699466,   -4.90083175,
         -0.        ,   -0.        ,  -24.53122626,  -10.17127678,
        -33.61686561,  -25.61686373,  -16.35415084,  -14.53702297,
        -48.15388858,   -0.43978378,  -30.8911738 ,  -18.17127871,
        170.95491272,  -15.4455869 ,  -15.4455869 ,  -16.35415084,
        -20.89697052,  147.33225118,  -32.23952198,  -51.31936465,
        -10.90276723,  -10.90276723, -101.3839682 ,  -70.86798