In [1]:
import torch
import os
import sys
sys.path.append("../core/datasets")
sys.path.append("../core/utils")

from pfdelta_dataset import PFDeltaDataset, PFDeltaGNS
from losses_to_test import PowerBalanceLoss, GNSPowerBalanceLoss 

In [2]:
dataset_GNS = PFDeltaGNS(
    root_dir = "final_data_no_exp", 
    case_name = "case57",
    force_reload = True, 
    max_samples = 10
)

Processing...


Processing combined data for task 1.1
Processing split: GNS 1.1 none train (10 files)


Building train data: 100%|██████████| 10/10 [00:00<00:00, 193.77it/s]


Processing split: GNS 1.1 none val (10 files)


Building val data: 100%|██████████| 10/10 [00:00<00:00, 216.39it/s]


Processing split: GNS 1.1 none test (10 files)


Building test data: 100%|██████████| 10/10 [00:00<00:00, 222.93it/s]


Processing split: GNS 1.1 n-1 train (0 files)


Building train data: 0it [00:00, ?it/s]


Processing split: GNS 1.1 n-2 train (0 files)


Building train data: 0it [00:00, ?it/s]


Collating combined train data with 10 samples
Saved combined train data with 10 samples
Collating combined val data with 10 samples
Saved combined val data with 10 samples
Collating combined test data with 10 samples
Saved combined test data with 10 samples
Loading train dataset from final_data_no_exp/processed/combined_task_1.1_GNS_case57/train.pt


Done!


In [3]:
dataset_GNS[0]

HeteroData(
  bus={
    x=[57, 2],
    y=[57, 2],
    bus_gen=[57, 2],
    bus_demand=[57, 2],
    bus_voltages=[57, 2],
    bus_type=[57],
    shunt=[57, 2],
    x_gns=[57, 2],
    v=[57],
    theta=[57],
    pd=[57],
    qd=[57],
    pg=[57],
    qg=[57],
    delta_p=[57],
    delta_q=[57],
  },
  gen={
    limits=[7, 4],
    generation=[7, 2],
    slack_gen=[7],
    num_nodes=7,
  },
  load={
    demand=[42, 2],
    num_nodes=42,
  },
  (bus, branch, bus)={
    edge_index=[2, 80],
    edge_attr=[80, 8],
    edge_label=[80, 4],
  },
  (gen, gen_link, bus)={ edge_index=[2, 7] },
  (bus, gen_link, gen)={ edge_index=[2, 7] },
  (load, load_link, bus)={ edge_index=[2, 42] },
  (bus, load_link, load)={ edge_index=[2, 42] }
)

In [4]:
dataset_GNS[0]["bus", "branch", "bus"].edge_attr

tensor([[8.3000e-03, 2.8000e-02, 0.0000e+00, 6.4500e-02, 0.0000e+00, 6.4500e-02,
         1.0000e+00, 0.0000e+00],
        [2.9800e-02, 8.5000e-02, 0.0000e+00, 4.0900e-02, 0.0000e+00, 4.0900e-02,
         1.0000e+00, 0.0000e+00],
        [1.1200e-02, 3.6600e-02, 0.0000e+00, 1.9000e-02, 0.0000e+00, 1.9000e-02,
         1.0000e+00, 0.0000e+00],
        [6.2500e-02, 1.3200e-01, 0.0000e+00, 1.2900e-02, 0.0000e+00, 1.2900e-02,
         1.0000e+00, 0.0000e+00],
        [4.3000e-02, 1.4800e-01, 0.0000e+00, 1.7400e-02, 0.0000e+00, 1.7400e-02,
         1.0000e+00, 0.0000e+00],
        [2.0000e-02, 1.0200e-01, 0.0000e+00, 1.3800e-02, 0.0000e+00, 1.3800e-02,
         1.0000e+00, 0.0000e+00],
        [3.3900e-02, 1.7300e-01, 0.0000e+00, 2.3500e-02, 0.0000e+00, 2.3500e-02,
         1.0000e+00, 0.0000e+00],
        [9.9000e-03, 5.0500e-02, 0.0000e+00, 2.7400e-02, 0.0000e+00, 2.7400e-02,
         1.0000e+00, 0.0000e+00],
        [3.6900e-02, 1.6790e-01, 0.0000e+00, 2.2000e-02, 0.0000e+00, 2.2000e-02,

In [5]:
# Setup output dict
delta_P_GNS, delta_Q_GNS, _, flows_GNS = GNSPowerBalanceLoss()(dataset_GNS[0], layer_loss=True)
_, delta_P, delta_Q, flows_reg = PowerBalanceLoss("GNS")({}, dataset_GNS[0])

tensor([0.0645, 0.0409, 0.0190, 0.0129, 0.0174, 0.0138, 0.0235, 0.0274, 0.0220,
        0.0109, 0.0386, 0.0203, 0.0055, 0.0115, 0.0494, 0.0273, 0.0143, 0.0272,
        0.0000, 0.0000, 0.0062, 0.0097, 0.0164, 0.0094, 0.0302, 0.0108, 0.0238,
        0.0074, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0042, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0016, 0.0008, 0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0010, 0.0000, 0.0000, 0.0016, 0.0000, 0.0024, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0020,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0015, 0.0000, 0.0000])
tensor([0.0645, 0.0409, 0.0190, 0.0129, 0.0174, 0.0138, 0.0235, 0.0274, 0.0220,
        0.0109, 0.0386, 0.0203, 0.0055, 0.0115, 0.0494, 0.0273, 0.0143, 0.0272,
        0.0000, 0.0000, 0.0062, 0.0097, 0.0164, 0.0094, 0.0302, 0.0108, 0.0238,
        0.0074, 0.0000, 0.0000, 0.0000, 0.0000,

In [6]:
# check that flows match
TOL = 1e-04
print(torch.allclose(delta_P_GNS, torch.zeros_like(delta_P_GNS), atol=TOL))
print(torch.allclose(delta_Q_GNS, torch.zeros_like(delta_Q_GNS), atol=TOL))

False
False


In [7]:
print(torch.allclose(delta_P, torch.zeros_like(delta_P), atol=TOL))
print(torch.allclose(delta_Q, torch.zeros_like(delta_Q), atol=TOL))

False
False


In [10]:
delta_P

tensor([ 1.7898e+01, -3.8049e+00, -2.2002e-01,  4.4189e-01, -1.3503e-01,
        -1.3295e+00,  9.9236e-02, -4.2393e+00, -1.3124e+00, -4.3851e-01,
         1.4636e-01,  4.3040e+00, -1.9644e-01, -1.6992e-01, -3.9057e-01,
        -2.0926e-01, -1.2095e-01, -8.7715e-01, -1.1208e-01, -1.6192e-02,
         0.0000e+00,  0.0000e+00, -2.0042e-01,  0.0000e+00, -8.7200e-02,
         0.0000e+00, -1.4651e-01, -4.6951e-02, -1.4405e+00, -4.0046e-02,
        -3.9738e-02, -3.5240e-02, -9.3247e-02,  0.0000e+00, -1.5937e-01,
         0.0000e+00,  0.0000e+00, -8.9030e-02,  0.0000e+00,  0.0000e+00,
        -2.2037e-01, -1.1134e-01, -3.2973e-01, -7.4850e-02,  0.0000e+00,
         0.0000e+00, -3.3534e-01,  0.0000e+00, -1.1304e-01, -2.4332e-01,
        -2.8429e-01, -3.3841e-01, -1.0331e-01, -8.6490e-02, -9.7828e-02,
        -9.2959e-02, -9.0031e-02])

In [11]:
delta_P_GNS

tensor([ 1.7898e+01, -3.8049e+00, -2.2002e-01,  4.4189e-01, -1.3503e-01,
        -1.3295e+00,  9.9236e-02, -4.2393e+00, -1.3124e+00, -4.3851e-01,
         1.4636e-01,  4.3040e+00, -1.9644e-01, -1.6992e-01, -3.9057e-01,
        -2.0926e-01, -1.2095e-01, -8.7715e-01, -1.1208e-01, -1.6192e-02,
        -2.2245e-09,  0.0000e+00, -2.0042e-01, -3.6529e-08, -8.7200e-02,
         3.8099e-08, -1.4651e-01, -4.6951e-02, -1.4405e+00, -4.0046e-02,
        -3.9738e-02, -3.5240e-02, -9.3247e-02,  1.2062e-09, -1.5937e-01,
         0.0000e+00,  0.0000e+00, -8.9030e-02,  6.7179e-10,  1.6740e-09,
        -2.2037e-01, -1.1134e-01, -3.2973e-01, -7.4850e-02, -1.9767e-08,
        -6.6079e-08, -3.3534e-01,  0.0000e+00, -1.1304e-01, -2.4332e-01,
        -2.8429e-01, -3.3841e-01, -1.0331e-01, -8.6490e-02, -9.7828e-02,
        -9.2959e-02, -9.0031e-02])

In [9]:
print(torch.allclose(delta_P, delta_P_GNS, atol=TOL))
print(torch.allclose(delta_Q, delta_Q_GNS, atol=TOL))

True
True


In [8]:
print(torch.allclose(flows_GNS[0], flows_reg[0], atol=TOL))
print(torch.allclose(flows_GNS[1], flows_reg[1], atol=TOL))
print(torch.allclose(flows_GNS[2], flows_reg[2], atol=TOL))
print(torch.allclose(flows_GNS[3], flows_reg[3], atol=TOL))

True
True
True
True
